interface Person {
	name: String!
	age: Int!
}

type Employee implements Person {
	name: String!
	age: Int!
}

type Coder implements Person {
	name: String!
	age: Int!
}

extend type Query {
	getPerson: Person
}
